export const DISTRICTS = ['Bagerhat', 'Bandarban', 'Barguna', 'Barishal', 'Bhola', 'Bogra', 'Brahmanbaria', 'Chandpur', 'Chapainawabganj', 'Chattogram', 'Chuadanga', 'Cumilla', 'Cox\'s Bazar', 'Dhaka', 'Dinajpur', 'Faridpur', 'Feni', 'Gaibandha', 'Gazipur', 'Gopalganj', 'Habiganj', 'Jamalpur', 'Jessore', 'Jhalokati', 'Jhenaidah', 'Joypurhat', 'Khagrachari', 'Khulna', 'Kishoreganj', 'Kurigram', 'Kushtia', 'Lakshmipur', 'Lalmonirhat', 'Madaripur', 'Magura', 'Manikganj', 'Meherpur', 'Moulvibazar', 'Munshiganj', 'Mymensingh', 'Naogaon', 'Narail', 'Narayanganj', 'Narsingdi', 'Natore', 'Netrokona', 'Nilphamari', 'Noakhali', 'Pabna', 'Panchagarh', 'Patuakhali', 'Pirojpur', 'Rajbari', 'Rajshahi', 'Rangamati', 'Rangpur', 'Satkhira', 'Shariatpur', 'Sherpur', 'Sirajganj', 'Sunamganj', 'Sylhet', 'Tangail', 'Thakurgaon'] as const;

export type District = (typeof DISTRICTS)[number];

export const UPAZILA: { district: string; upazila: string[] }[] = [
    { district: 'Bagerhat', upazila: ['Bagerhat Sadar', 'Chitalmari', 'Fakirhat', 'Kachua', 'Mollahat', 'Mongla', 'Morrelganj', 'Rampal', 'Sarankhola'] },
    { district: 'Bandarban', upazila: ['Ali Kadam', 'Bandarban Sadar', 'Lama', 'Naikhongchhari', 'Rowangchhari', 'Ruma', 'Thanchi'] },
    { district: 'Barguna', upazila: ['Amtali', 'Bamna', 'Barguna Sadar', 'Betagi', 'Patharghata', 'Taltali'] },
    { district: 'Barishal', upazila: ['Agailjhara', 'Babuganj', 'Bakerganj', 'Banaripara', 'Barishal Sadar', 'Gaurnadi', 'Hizla', 'Mehendiganj', 'Muladi', 'Wazirpur', 'Airport Thana', 'Kotwali Thana', 'Kawnia Thana', 'Bandar Thana'] },
    { district: 'Bhola', upazila: ['Bhola Sadar', 'Burhanuddin', 'Char Fasson', 'Daulatkhan', 'Lalmohan', 'Manpura', 'Tazumuddin'] },
    { district: 'Bogra', upazila: ['Adamdighi', 'Bogra Sadar', 'Dhunat', 'Dhupchanchia', 'Gabtali', 'Kahaloo', 'Nandigram', 'Sariakandi', 'Shajahanpur', 'Sherpur', 'Shibganj', 'Sonatola'] },
    { district: 'Brahmanbaria', upazila: ['Akhaura', 'Ashuganj', 'Bancharampur', 'Brahmanbaria Sadar', 'Bijoynagar', 'Kasba', 'Nabinagar', 'Nasirnagar', 'Sarail'] },
    { district: 'Chandpur', upazila: ['Chandpur Sadar', 'Faridganj', 'Haimchar', 'Haziganj', 'Kachua', 'Matlab Dakshin', 'Matlab Uttar', 'Shahrasti'] },
    { district: 'Chapainawabganj', upazila: ['Bholahat', 'Gomastapur', 'Nachole', 'Nawabganj Sadar', 'Shibganj'] },
    { district: 'Chattogram', upazila: ['Anwara', 'Banshkhali', 'Boalkhali', 'Chandanaish', 'Fatikchhari', 'Hathazari', 'Karnaphuli', 'Lohagara', 'Mirsharai', 'Patiya', 'Rangunia', 'Raozan', 'Sandwip', 'Satkania', 'Sitakunda', 'Akbarshah Thana', 'Bakalia Thana', 'Bayazid Thana', 'Chandgaon Thana', 'Double Mooring Thana', 'EPZ Thana', 'Halishahar Thana', 'Khulshi Thana', 'Kotwali Thana', 'Pahartali Thana', 'Panchlaish Thana', 'Patenga Thana'] },
    { district: 'Chuadanga', upazila: ['Alamdanga', 'Chuadanga Sadar', 'Damurhuda', 'Jibannagar'] },
    { district: 'Cumilla', upazila: ['Barura', 'Brahmanpara', 'Burichang', 'Chandina', 'Chauddagram', 'Cumilla Adarsha Sadar', 'Cumilla Sadar Dakshin', 'Daudkandi', 'Debidwar', 'Homna', 'Laksam', 'Lalmai', 'Meghna', 'Monohargonj', 'Muradnagar', 'Nangalkot', 'Titas'] },
    { district: 'Cox\'s Bazar', upazila: ['Chakaria', 'Cox\'s Bazar Sadar', 'Eidgaon', 'Kutubdia', 'Maheshkhali', 'Pekua', 'Ramu', 'Teknaf', 'Ukhia'] },
    { district: 'Dhaka', upazila: ['Dhamrai', 'Dohar', 'Keraniganj', 'Nawabganj', 'Savar', 'Adabor Thana', 'Badda Thana', 'Banani Thana', 'Bangsal Thana', 'Cantonment Thana', 'Chalkbazar Thana', 'Dakshinkhan Thana', 'Darus Salam Thana', 'Demra Thana', 'Dhanmondi Thana', 'Gendaria Thana', 'Gulshan Thana', 'Hazaribagh Thana', 'Jatrabari Thana', 'Kadamtali Thana', 'Kafrul Thana', 'Kalabagan Thana', 'Kamrangirchar Thana', 'Khilgaon Thana', 'Khilkhet Thana', 'Kotwali Thana', 'Lalbagh Thana', 'Mirpur Thana', 'Mohammadpur Thana', 'Motijheel Thana', 'Mughda Thana', 'New Market Thana', 'Pallabi Thana', 'Paltan Thana', 'Ramna Thana', 'Rampura Thana', 'Sabujbagh Thana', 'Shah Ali Thana', 'Shahbagh Thana', 'Sher-e-Bangla Nagar Thana', 'Shyampur Thana', 'Sutrapur Thana', 'Tejgaon Thana', 'Tejgaon Industrial Area Thana', 'Turag Thana', 'Uttara East Thana', 'Uttara West Thana', 'Uttarkhan Thana', 'Vatara Thana', 'Wari Thana'] },
    { district: 'Dinajpur', upazila: ['Birampur', 'Birganj', 'Biral', 'Bochaganj', 'Chirirbandar', 'Dinajpur Sadar', 'Ghoraghat', 'Hakimpur', 'Kaharole', 'Khansama', 'Nawabganj', 'Parbatipur', 'Phulbari'] },
    { district: 'Faridpur', upazila: ['Alfadanga', 'Bhanga', 'Boalmari', 'Charbhadrasan', 'Faridpur Sadar', 'Madhukhali', 'Nagarkanda', 'Sadarpur', 'Saltha'] },
    { district: 'Feni', upazila: ['Chhagalnaiya', 'Daganbhuiyan', 'Feni Sadar', 'Fulgazi', 'Parshuram', 'Sonagazi'] },
    { district: 'Gaibandha', upazila: ['Fullchhari', 'Gaibandha Sadar', 'Gobindaganj', 'Palashbari', 'Sadullapur', 'Saghata', 'Sundarganj'] },
    { district: 'Gazipur', upazila: ['Gazipur Sadar', 'Kaliakair', 'Kaliganj', 'Kapasia', 'Sreepur', 'Gacha Thana', 'Pubail Thana', 'Konabari Thana', 'Basan Thana', 'Tongi East Thana', 'Tongi West Thana'] },
    { district: 'Gopalganj', upazila: ['Gopalganj Sadar', 'Kashiani', 'Kotalipara', 'Muksudpur', 'Tungipara'] },
    { district: 'Habiganj', upazila: ['Ajmiriganj', 'Bahubal', 'Baniyachong', 'Chunarughat', 'Habiganj Sadar', 'Lakhai', 'Madhabpur', 'Nabiganj', 'Sayestaganj'] },
    { district: 'Jamalpur', upazila: ['Baksiganj', 'Dewanganj', 'Islampur', 'Jamalpur Sadar', 'Madarganj', 'Melandaha', 'Sarishabari'] },
    { district: 'Jessore', upazila: ['Abhaynagar', 'Bagherpara', 'Chougacha', 'Jessore Sadar', 'Jhikargacha', 'Keshabpur', 'Manirampur', 'Sharsha'] },
    { district: 'Jhalokati', upazila: ['Jhalokati Sadar', 'Kathalia', 'Nalchity', 'Rajapur'] },
    { district: 'Jhenaidah', upazila: ['Harinakunda', 'Jhenaidah Sadar', 'Kaliganj', 'Kotchandpur', 'Maheshpur', 'Shailkupa'] },
    { district: 'Joypurhat', upazila: ['Akkelpur', 'Joypurhat Sadar', 'Kalai', 'Khetlal', 'Panchbibi'] },
    { district: 'Khagrachari', upazila: ['Dighinala', 'Guimara', 'Khagrachari Sadar', 'Lakshmichhari', 'Mahalchhari', 'Manikchhari', 'Matiranga', 'Panchhari', 'Ramgarh'] },
    { district: 'Khulna', upazila: ['Batiaghata', 'Dacope', 'Dumuria', 'Dighalia', 'Koyra', 'Paikgacha', 'Phultala', 'Rupsha', 'Terokhada', 'Daulatpur Thana', 'Khalishpur Thana', 'Khan Jahan Ali Thana', 'Khulna Sadar Thana', 'Sonadanga Thana', 'Harintana Thana'] },
    { district: 'Kishoreganj', upazila: ['Austagram', 'Bajitpur', 'Bhairab', 'Hossainpur', 'Itna', 'Karimganj', 'Katiadi', 'Kishoreganj Sadar', 'Kuliarchar', 'Mithamain', 'Nikli', 'Pakundia', 'Tarail'] },
    { district: 'Kurigram', upazila: ['Bhurungamari', 'Char Rajibpur', 'Chilmari', 'Kurigram Sadar', 'Nageshwari', 'Phulbari', 'Rajarhat', 'Raumari', 'Ulipur'] },
    { district: 'Kushtia', upazila: ['Bheramara', 'Daulatpur', 'Khoksa', 'Kumarkhali', 'Kushtia Sadar', 'Mirpur'] },
    { district: 'Lakshmipur', upazila: ['Kamalnagar', 'Lakshmipur Sadar', 'Raipur', 'Ramganj', 'Ramgati'] },
    { district: 'Lalmonirhat', upazila: ['Aditmari', 'Hatibandha', 'Kaliganj', 'Lalmonirhat Sadar', 'Patgram'] },
    { district: 'Madaripur', upazila: ['Dasar', 'Kalkini', 'Madaripur Sadar', 'Rajoir', 'Shibchar'] },
    { district: 'Magura', upazila: ['Magura Sadar', 'Mohammadpur', 'Shalikha', 'Sreepur'] },
    { district: 'Manikganj', upazila: ['Daulatpur', 'Ghior', 'Harirampur', 'Manikganj Sadar', 'Saturia', 'Shivalaya', 'Singair'] },
    { district: 'Meherpur', upazila: ['Gangni', 'Meherpur Sadar', 'Mujibnagar'] },
    { district: 'Moulvibazar', upazila: ['Barlekha', 'Juri', 'Kamalganj', 'Kulaura', 'Moulvibazar Sadar', 'Rajnagar', 'Sreemangal'] },
    { district: 'Munshiganj', upazila: ['Gazaria', 'Lohajang', 'Munshiganj Sadar', 'Sirajdikhan', 'Sreenagar', 'Tongibari'] },
    { district: 'Mymensingh', upazila: ['Bhaluka', 'Dhobaura', 'Fulbaria', 'Gaffargaon', 'Gauripur', 'Haluaghat', 'Ishwarganj', 'Mymensingh Sadar', 'Muktagacha', 'Nandail', 'Phulpur', 'Tarakanda', 'Trishal'] },
    { district: 'Naogaon', upazila: ['Atrai', 'Badalgachhi', 'Dhamoirhat', 'Manda', 'Mahadebpur', 'Naogaon Sadar', 'Niamatpur', 'Patnitala', 'Porsha', 'Raninagar', 'Sapahar'] },
    { district: 'Narail', upazila: ['Kalia', 'Lohagara', 'Narail Sadar'] },
    { district: 'Narayanganj', upazila: ['Araihazar', 'Bandar', 'Narayanganj Sadar', 'Rupganj', 'Sonargaon', 'Siddhirganj Thana', 'Fatullah Thana'] },
    { district: 'Narsingdi', upazila: ['Belabo', 'Monohardi', 'Narsingdi Sadar', 'Palash', 'Raipura', 'Shibpur'] },
    { district: 'Natore', upazila: ['Bagatipara', 'Baraigram', 'Gurudaspur', 'Lalpur', 'Naldanga', 'Natore Sadar', 'Singra'] },
    { district: 'Netrokona', upazila: ['Atpara', 'Barhatta', 'Durgapur', 'Kalmakanda', 'Kendua', 'Khaliajuri', 'Madan', 'Mohanganj', 'Netrokona Sadar', 'Purbadhala'] },
    { district: 'Nilphamari', upazila: ['Dimla', 'Domar', 'Jaldhaka', 'Kishoreganj', 'Nilphamari Sadar', 'Saidpur'] },
    { district: 'Noakhali', upazila: ['Begumganj', 'Chatkhil', 'Companiganj', 'Hatiya', 'Kabirhat', 'Noakhali Sadar', 'Senbagh', 'Sonaimuri', 'Subarnachar'] },
    { district: 'Pabna', upazila: ['Atgharia', 'Bera', 'Bhangura', 'Chatmohar', 'Faridpur', 'Ishwardi', 'Pabna Sadar', 'Santhia', 'Sujanagar'] },
    { district: 'Panchagarh', upazila: ['Atwari', 'Boda', 'Debiganj', 'Panchagarh Sadar', 'Tetulia'] },
    { district: 'Patuakhali', upazila: ['Bauphal', 'Dashmina', 'Dumki', 'Galachipa', 'Kalapara', 'Mirzaganj', 'Patuakhali Sadar', 'Rangabali'] },
    { district: 'Pirojpur', upazila: ['Bhandaria', 'Indurkani', 'Kawkhali', 'Mathbaria', 'Nazirpur', 'Nesarabad (Swarupkati)', 'Pirojpur Sadar'] },
    { district: 'Rajbari', upazila: ['Baliakandi', 'Goalanda', 'Kalukhali', 'Pangsha', 'Rajbari Sadar'] },
    { district: 'Rajshahi', upazila: ['Bagha', 'Bagmara', 'Charghat', 'Durgapur', 'Godagari', 'Mohanpur', 'Paba', 'Puthia', 'Tanore', 'Boalia Thana', 'Motihar Thana', 'Rajpari Thana', 'Shah Makdum Thana'] },
    { district: 'Rangamati', upazila: ['Bagaichhari', 'Barkal', 'Belaichhari', 'Juraichhari', 'Kaptai', 'Kawkhali', 'Langadu', 'Naniyachar', 'Rajasthali', 'Rangamati Sadar'] },
    { district: 'Rangpur', upazila: ['Badarganj', 'Gangachhara', 'Kaunia', 'Mithapukur', 'Pirgachha', 'Pirganj', 'Rangpur Sadar', 'Taraganj', 'Kotwali Thana', 'Parshuram Thana', 'Haragach Thana'] },
    { district: 'Satkhira', upazila: ['Assasuni', 'Debhata', 'Kalaroa', 'Kaliganj', 'Satkhira Sadar', 'Shyamnagar', 'Tala'] },
    { district: 'Shariatpur', upazila: ['Bhedarganj', 'Damudya', 'Gosairhat', 'Naria', 'Shariatpur Sadar', 'Zajira'] },
    { district: 'Sherpur', upazila: ['Jhenaigati', 'Nakla', 'Nalitabari', 'Sherpur Sadar', 'Sreebardi'] },
    { district: 'Sirajganj', upazila: ['Belkuchi', 'Chauhali', 'Kamarkhanda', 'Kazipur', 'Raiganj', 'Shahjadpur', 'Sirajganj Sadar', 'Tarash', 'Ullahpara'] },
    { district: 'Sunamganj', upazila: ['Bishwamarpur', 'Chhatak', 'Derai', 'Dharamapasha', 'Dowarabazar', 'Jagannathpur', 'Jamalganj', 'Madhyanagar', 'Shantiganj', 'Sullah', 'Sunamganj Sadar', 'Tahirpur'] },
    { district: 'Sylhet', upazila: ['Balaganj', 'Beanibazar', 'Bishwanath', 'Fenchuganj', 'Golapganj', 'Gowainghat', 'Jaintiapur', 'Kanaighat', 'Osmani Nagar', 'South Surma', 'Sylhet Sadar', 'Zakiganj', 'Companiganj', 'Shahparan Thana', 'Moglabazar Thana', 'Airport Thana'] },
    { district: 'Tangail', upazila: ['Basail', 'Bhuapur', 'Delduar', 'Dhanbari', 'Ghatail', 'Gopalpur', 'Kalihati', 'Madhupur', 'Mirzapur', 'Nagarpur', 'Sakhipur', 'Tangail Sadar'] },
    { district: 'Thakurgaon', upazila: ['Baliadangi', 'Haripur', 'Pirganj', 'Ranisankail', 'Thakurgaon Sadar'] }
];

export function getUpazilasForDistrict(district: string): string[] {
  const row = UPAZILA.find((d) => d.district === district);
  return row ? row.upazila : [];
}
